# Lab 01-1 Tensor Manipulation 1

### 1D Array with NumPy

In [1]:
import numpy as np
import torch

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print("Rank of t: ", t.ndim)
print("Shape of t: ", t.shape)

Rank of t:  1
Shape of t:  (7,)


In [5]:
print("t[0] t[1] t[-1] = ", t[0], t[1], t[-1]) #Element
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) # Slicing
print("t[:2] t[3:] = ", t[:2], t[3:]) # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


## 2D Array with NumPy

In [6]:
t = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.], [10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


## 1D Array with PyTorch

In [9]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [10]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape ==>> shape함수나 size함수나 똑같은 값이 나온다.
print(t[0], t[1], t[-1])   # Element
print(t[2:5], t[4:-1])     # Slicing
print(t[:2], t[3:])        # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D Array with PyTorch

In [11]:
t = torch.FloatTensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       [10.,11.,12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [13]:
print(t.dim()) # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1]) # 첫번째 차원은 다 가져오고, 맨마지막 차원빼고 다 가져와!

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Pytorch는 어떻게 다루는가?

### 첫번째 기능 : Broadcasting - 연산 시 자동적으로 size(shape)을 맞춰준다

In [14]:
# Same shape
m1 = torch.FloatTensor([[3, 3]]) # lm1l = (1,2)
m2 = torch.FloatTensor([[2, 2]]) # lm1l = lm2l
print(m1 + m2)

tensor([[5., 5.]])


In [15]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]]) # lm1l = (1,2)
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]으로 broadcasting
print(m1 + m2)

tensor([[4., 5.]])


In [16]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # lm1l = (1,2)
m2 = torch.FloatTensor([[3], [4]]) # lm2l = (2,1)
print(m1 + m2) # 원래는 m1, m2의 shape이 달라 덧셈은 안되지만, broadcasting되서 m1도 2x2, m2도 2x2로 변하게 된다.

tensor([[4., 5.],
        [5., 6.]])


- broadcasting 사용 시에는 어디서 에러가 있는지, 잘못입력되었는지 알 수 없이 정상적으로 연산이 종료되기 때문에 사용 시 유의해야한다.

## Multiplication vs Matrix Multiplication
- 곱셈(원소)
- 행렬곱
- 딥러닝은 행렬곱을 굉장히 많이 사용하는 알고리즘이 많다.
- 그렇기에 잘 이해하고 구현하는 것이 중요하다.

In [17]:
print()
print('---------------')
print('Mul vss Matmul')
print('---------------')
m1 = torch.FloatTensor([[1,2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1 : ', m1.shape)
print('Shape of Matrix 2 : ', m2.shape)
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1,2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1 : ', m1.shape)
print('Shape of Matrix 2 : ', m2.shape)
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


---------------
Mul vss Matmul
---------------
Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Mean
- 평균
- int형에는 쓸 수 없다.
- 기본적으로는 FloatTensor를 이용해 Float type의 Tensor를 선언하기에 이것만 유의해주면 된다.

In [18]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [19]:
# Can't use mean()) on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Sum

In [22]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [23]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max and Argmax

In [24]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [25]:
print(t.max()) # Return one value : max

tensor(4.)


- The max operator in pytorch returns 2 values when called with dimension specified.
- The first value is the maximum value, and the second value is the argmax: the index of the element with maximum value.

In [26]:
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [27]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
